version: '3'

services:
  consul: 
    image: consul:latest
    networks:
      - consul-demo
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"
    command: "agent -server -bootstrap -ui -client 0.0.0.0"

networks:
  consul-demo: